services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abcd2024
      - POSTGRES_DB=covid19m
    ports:
      - 5432:5432

  app:
    image: c19api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abcd2024
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/covid19m
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=abcd2024
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8081:8081

  front:
    image: c19dashbord
    build:
      context: front/covid19dashbord
      dockerfile: Dockerfile
    container_name: front
    depends_on:
      - app
    ports:
      - 80:80